name: todo_app_crud
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  drift: ^2.14.0
  faker: ^2.1.0
  path: ^1.9.0
  path_provider: ^2.1.2
  sqlite3_flutter_libs: ^0.5.19+1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.8
  drift_dev: ^2.14.1
  lints: ^2.0.0
  test: ^1.21.0
